
/* Program generated by Cbasic 6.2.0 9879 */
#define XSCT_CBASIC

#ifndef XX_HANmessages_H
#define XX_HANmessages_H

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* PACKAGE HANmessages
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun,4,1,9)
******/
extern XCONST struct xPackageIdStruct yPacR_z_HANmessages__HANmessages;

extern void yInit_HANmessages (void);

/*****
* SYNTYPE AppID  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),2,2)
******/
#ifndef XTNOUSE_AppID
extern tSDLGenInfo ySDL_z_HANmessages_1I_AppID;
#endif
typedef SDL_Integer  z_HANmessages_1I_AppID;

/*****
* NEWTYPE AppType  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),5,9)
******/
#ifndef XTNOUSE_AppType
extern tSDLEnumInfo ySDL_z_HANmessages_1C_AppType;
#endif
typedef XENUM_TYPE z_HANmessages_1C_AppType;
#define z_HANmessages_1C0_CTRL 0
#define z_HANmessages_1C1_CRITICAL 1
#define z_HANmessages_1C2_NULL 2

/*****
* SYNTYPE DevPriority  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),10,2)
******/
#ifndef XTNOUSE_DevPriority
extern tSDLGenInfo ySDL_z_HANmessages_1J_DevPriority;
#endif
typedef SDL_Integer  z_HANmessages_1J_DevPriority;

/*****
* NEWTYPE AppArray  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),14,2)
******/
#ifndef XTNOUSE_AppArray
extern tSDLGArrayInfo ySDL_z_HANmessages_1D_AppArray;
#endif

typedef struct z_HANmessages_1D_AppArray_ystruct * z_HANmessages_1D_AppArray_yptr;
typedef struct z_HANmessages_1D_AppArray_ystruct {
  z_HANmessages_1D_AppArray_yptr Suc;
  z_HANmessages_1I_AppID Index;
  SDL_PId Data;
} z_HANmessages_1D_AppArray_yrec;
typedef struct {
  z_HANmessages_1D_AppArray_yptr First;
  z_HANmessages_1D_AppArray_yptr Last;
  int IsAssigned;
  SDL_PId Data;
} z_HANmessages_1D_AppArray;

/*****
* NEWTYPE TypeArray  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),18,2)
******/
#ifndef XTNOUSE_TypeArray
extern tSDLGArrayInfo ySDL_z_HANmessages_1E_TypeArray;
#endif

typedef struct z_HANmessages_1E_TypeArray_ystruct * z_HANmessages_1E_TypeArray_yptr;
typedef struct z_HANmessages_1E_TypeArray_ystruct {
  z_HANmessages_1E_TypeArray_yptr Suc;
  z_HANmessages_1I_AppID Index;
  z_HANmessages_1C_AppType Data;
} z_HANmessages_1E_TypeArray_yrec;
typedef struct {
  z_HANmessages_1E_TypeArray_yptr First;
  z_HANmessages_1E_TypeArray_yptr Last;
  int IsAssigned;
  z_HANmessages_1C_AppType Data;
} z_HANmessages_1E_TypeArray;

/*****
* NEWTYPE PryArray  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),26,2)
******/
#ifndef XTNOUSE_PryArray
extern tSDLGArrayInfo ySDL_z_HANmessages_1G_PryArray;
#endif

typedef struct z_HANmessages_1G_PryArray_ystruct * z_HANmessages_1G_PryArray_yptr;
typedef struct z_HANmessages_1G_PryArray_ystruct {
  z_HANmessages_1G_PryArray_yptr Suc;
  z_HANmessages_1I_AppID Index;
  z_HANmessages_1J_DevPriority Data;
} z_HANmessages_1G_PryArray_yrec;
typedef struct {
  z_HANmessages_1G_PryArray_yptr First;
  z_HANmessages_1G_PryArray_yptr Last;
  int IsAssigned;
  z_HANmessages_1J_DevPriority Data;
} z_HANmessages_1G_PryArray;

/*****
* SYNTYPE Charge  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),30,2)
******/
#ifndef XTNOUSE_Charge
extern tSDLGenInfo ySDL_z_HANmessages_1K_Charge;
#endif
typedef SDL_Real  z_HANmessages_1K_Charge;

/*****
* SYNTYPE Consumption  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),2,2)
******/
#ifndef XTNOUSE_Consumption
extern tSDLGenInfo ySDL_z_HANmessages_1L_Consumption;
#endif
typedef SDL_Real  z_HANmessages_1L_Consumption;

/*****
* SYNTYPE FULL  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),6,2)
******/
#ifndef XTNOUSE_FULL
extern tSDLGenInfo ySDL_z_HANmessages_1M_FULL;
#endif
typedef SDL_Real  z_HANmessages_1M_FULL;

/*****
* SYNTYPE Price  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),10,2)
******/
#ifndef XTNOUSE_Price
extern tSDLGenInfo ySDL_z_HANmessages_1N_Price;
#endif
typedef SDL_Real  z_HANmessages_1N_Price;

/*****
* SYNTYPE Storage  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),14,2)
******/
#ifndef XTNOUSE_Storage
extern tSDLGenInfo ySDL_z_HANmessages_1O_Storage;
#endif
typedef SDL_Real  z_HANmessages_1O_Storage;

/*****
* SYNTYPE BidID  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),18,2)
******/
#ifndef XTNOUSE_BidID
extern tSDLGenInfo ySDL_z_HANmessages_1P_BidID;
#endif
typedef SDL_Integer  z_HANmessages_1P_BidID;

/*****
* SYNTYPE RTPID  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),22,2)
******/
#ifndef XTNOUSE_RTPID
extern tSDLGenInfo ySDL_z_HANmessages_1Q_RTPID;
#endif
typedef SDL_Integer  z_HANmessages_1Q_RTPID;

/*****
* NEWTYPE SetID  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),26,2)
******/
#ifndef XTNOUSE_SetID
extern tSDLGenListInfo ySDL_z_HANmessages_1H_SetID;
#endif

typedef struct z_HANmessages_1H_SetID_ystruct *z_HANmessages_1H_SetID_yptr;
typedef struct z_HANmessages_1H_SetID_ystruct {
  z_HANmessages_1H_SetID_yptr Suc;
  z_HANmessages_1I_AppID Data;
} z_HANmessages_1H_SetID_yrec;
typedef struct {
  z_HANmessages_1H_SetID_yptr First;
  z_HANmessages_1H_SetID_yptr Last;
  int Length;
  int IsAssigned;
} z_HANmessages_1H_SetID;

/*****
* NEWTYPE ConsArray  (TYPE section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),22,2)
******/
#ifndef XTNOUSE_ConsArray
extern tSDLGArrayInfo ySDL_z_HANmessages_1F_ConsArray;
#endif

typedef struct z_HANmessages_1F_ConsArray_ystruct * z_HANmessages_1F_ConsArray_yptr;
typedef struct z_HANmessages_1F_ConsArray_ystruct {
  z_HANmessages_1F_ConsArray_yptr Suc;
  z_HANmessages_1I_AppID Index;
  z_HANmessages_1L_Consumption Data;
} z_HANmessages_1F_ConsArray_yrec;
typedef struct {
  z_HANmessages_1F_ConsArray_yptr First;
  z_HANmessages_1F_ConsArray_yptr Last;
  int IsAssigned;
  z_HANmessages_1L_Consumption Data;
} z_HANmessages_1F_ConsArray;

/*****
* SYNTYPE AppID  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),2,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1I_AppID;
#define ySrtN_z_HANmessages_1I_AppID  (&ySrtR_z_HANmessages_1I_AppID)
#endif

#define yAssF_z_HANmessages_1I_AppID(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_HANmessages_1I_AppID(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_HANmessages_1I_AppID(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1I_AppID(Expr1,Expr2) yMkAddr_SDL_Integer(yTstA_z_HANmessages_1I_AppID(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1I_AppID (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1I_AppID yTstA_z_HANmessages_1I_AppID
  (z_HANmessages_1I_AppID yExpr);
#else
#define yTstA_z_HANmessages_1I_AppID(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1I_AppID
#define ANY_z_HANmessages_1I_AppID ANY_for_syntype_AppID_not_implemented
#endif

/*****
* NEWTYPE AppType  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),5,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1C_AppType;
#define ySrtN_z_HANmessages_1C_AppType  (&ySrtR_z_HANmessages_1C_AppType)
#endif

#define yAssF_z_HANmessages_1C_AppType(V,E,A)  V = E
#define yEqF_z_HANmessages_1C_AppType(Expr1,Expr2)  ((Expr1) == (Expr2))
#define yNEqF_z_HANmessages_1C_AppType(Expr1,Expr2)  ((Expr1) != (Expr2))
#define yMkAddr_z_HANmessages_1C_AppType yMkAddr_GenericShortEnum
#ifndef ANY_z_HANmessages_1C_AppType
#define ANY_z_HANmessages_1C_AppType (z_HANmessages_1C_AppType)(0 + \
  GETINTRAND%((int)(z_HANmessages_1C2_NULL)+1))
#endif
#define z_HANmessages_1C6_copy(P)  (P)

/*****
* SYNTYPE DevPriority  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),10,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1J_DevPriority;
#define ySrtN_z_HANmessages_1J_DevPriority  (&ySrtR_z_HANmessages_1J_DevPriority)
#endif

#define yAssF_z_HANmessages_1J_DevPriority(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_HANmessages_1J_DevPriority(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_HANmessages_1J_DevPriority(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1J_DevPriority(Expr1,Expr2) yMkAddr_SDL_Integer(yTstA_z_HANmessages_1J_DevPriority(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1J_DevPriority (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1J_DevPriority yTstA_z_HANmessages_1J_DevPriority
  (z_HANmessages_1J_DevPriority yExpr);
#else
#define yTstA_z_HANmessages_1J_DevPriority(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1J_DevPriority
#define ANY_z_HANmessages_1J_DevPriority (z_HANmessages_1J_DevPriority)(0 + \
  GETINTRAND%(2+1))
#endif

/*****
* NEWTYPE AppArray  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),14,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1D_AppArray;
#define ySrtN_z_HANmessages_1D_AppArray  (&ySrtR_z_HANmessages_1D_AppArray)
#endif

#define yAss_z_HANmessages_1D_AppArray(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_HANmessages_1D_AppArray)
#define yAssF_z_HANmessages_1D_AppArray(V,E,A)  yAss_z_HANmessages_1D_AppArray(&(V),E,A)
#define yEq_z_HANmessages_1D_AppArray(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_HANmessages_1D_AppArray)
#define yEqF_z_HANmessages_1D_AppArray(Expr1,Expr2)  yEq_z_HANmessages_1D_AppArray(Expr1,Expr2)
#define yNEqF_z_HANmessages_1D_AppArray(Expr1,Expr2)  ( !( yEq_z_HANmessages_1D_AppArray(Expr1,Expr2)) )
#define yFree_z_HANmessages_1D_AppArray(P) GenericFreeSort((void **)(P), (tSDLTypeInfo *)&ySDL_z_HANmessages_1D_AppArray)
#define yExtr_z_HANmessages_1D_AppArray(V1,V2) ((SDL_PId *)GenGArray_Extract((xGArray_Type *)V1,V2,&ySDL_z_HANmessages_1D_AppArray))
#define yAddr_z_HANmessages_1D_AppArray(V1,V2) ((SDL_PId *)GenGArray_Modify((xGArray_Type *)V1,V2,&ySDL_z_HANmessages_1D_AppArray))
#ifndef ANY_z_HANmessages_1D_AppArray
#define ANY_z_HANmessages_1D_AppArray(R) (z_HANmessages_1D_AppArray *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_HANmessages_1D_AppArray)
#endif
#define z_HANmessages_1D6_copy(P,R)  (P)

/*****
* NEWTYPE TypeArray  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),18,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1E_TypeArray;
#define ySrtN_z_HANmessages_1E_TypeArray  (&ySrtR_z_HANmessages_1E_TypeArray)
#endif

#define yAss_z_HANmessages_1E_TypeArray(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_HANmessages_1E_TypeArray)
#define yAssF_z_HANmessages_1E_TypeArray(V,E,A)  yAss_z_HANmessages_1E_TypeArray(&(V),E,A)
#define yEq_z_HANmessages_1E_TypeArray(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_HANmessages_1E_TypeArray)
#define yEqF_z_HANmessages_1E_TypeArray(Expr1,Expr2)  yEq_z_HANmessages_1E_TypeArray(Expr1,Expr2)
#define yNEqF_z_HANmessages_1E_TypeArray(Expr1,Expr2)  ( !( yEq_z_HANmessages_1E_TypeArray(Expr1,Expr2)) )
#define yFree_z_HANmessages_1E_TypeArray(P) GenericFreeSort((void **)(P), (tSDLTypeInfo *)&ySDL_z_HANmessages_1E_TypeArray)
#define yExtr_z_HANmessages_1E_TypeArray(V1,V2) ((z_HANmessages_1C_AppType *)GenGArray_Extract((xGArray_Type *)V1,V2,&ySDL_z_HANmessages_1E_TypeArray))
#define yAddr_z_HANmessages_1E_TypeArray(V1,V2) ((z_HANmessages_1C_AppType *)GenGArray_Modify((xGArray_Type *)V1,V2,&ySDL_z_HANmessages_1E_TypeArray))
#ifndef ANY_z_HANmessages_1E_TypeArray
#define ANY_z_HANmessages_1E_TypeArray(R) (z_HANmessages_1E_TypeArray *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_HANmessages_1E_TypeArray)
#endif
#define z_HANmessages_1E6_copy(P,R)  (P)

/*****
* NEWTYPE ConsArray  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),22,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1F_ConsArray;
#define ySrtN_z_HANmessages_1F_ConsArray  (&ySrtR_z_HANmessages_1F_ConsArray)
#endif

#define yAss_z_HANmessages_1F_ConsArray(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_HANmessages_1F_ConsArray)
#define yAssF_z_HANmessages_1F_ConsArray(V,E,A)  yAss_z_HANmessages_1F_ConsArray(&(V),E,A)
#define yEq_z_HANmessages_1F_ConsArray(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_HANmessages_1F_ConsArray)
#define yEqF_z_HANmessages_1F_ConsArray(Expr1,Expr2)  yEq_z_HANmessages_1F_ConsArray(Expr1,Expr2)
#define yNEqF_z_HANmessages_1F_ConsArray(Expr1,Expr2)  ( !( yEq_z_HANmessages_1F_ConsArray(Expr1,Expr2)) )
#define yFree_z_HANmessages_1F_ConsArray(P) GenericFreeSort((void **)(P), (tSDLTypeInfo *)&ySDL_z_HANmessages_1F_ConsArray)
#define yExtr_z_HANmessages_1F_ConsArray(V1,V2) ((z_HANmessages_1L_Consumption *)GenGArray_Extract((xGArray_Type *)V1,V2,&ySDL_z_HANmessages_1F_ConsArray))
#define yAddr_z_HANmessages_1F_ConsArray(V1,V2) ((z_HANmessages_1L_Consumption *)GenGArray_Modify((xGArray_Type *)V1,V2,&ySDL_z_HANmessages_1F_ConsArray))
#ifndef ANY_z_HANmessages_1F_ConsArray
#define ANY_z_HANmessages_1F_ConsArray(R) (z_HANmessages_1F_ConsArray *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_HANmessages_1F_ConsArray)
#endif
#define z_HANmessages_1F6_copy(P,R)  (P)

/*****
* NEWTYPE PryArray  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),26,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1G_PryArray;
#define ySrtN_z_HANmessages_1G_PryArray  (&ySrtR_z_HANmessages_1G_PryArray)
#endif

#define yAss_z_HANmessages_1G_PryArray(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_HANmessages_1G_PryArray)
#define yAssF_z_HANmessages_1G_PryArray(V,E,A)  yAss_z_HANmessages_1G_PryArray(&(V),E,A)
#define yEq_z_HANmessages_1G_PryArray(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_HANmessages_1G_PryArray)
#define yEqF_z_HANmessages_1G_PryArray(Expr1,Expr2)  yEq_z_HANmessages_1G_PryArray(Expr1,Expr2)
#define yNEqF_z_HANmessages_1G_PryArray(Expr1,Expr2)  ( !( yEq_z_HANmessages_1G_PryArray(Expr1,Expr2)) )
#define yFree_z_HANmessages_1G_PryArray(P) GenericFreeSort((void **)(P), (tSDLTypeInfo *)&ySDL_z_HANmessages_1G_PryArray)
#define yExtr_z_HANmessages_1G_PryArray(V1,V2) ((z_HANmessages_1J_DevPriority *)GenGArray_Extract((xGArray_Type *)V1,V2,&ySDL_z_HANmessages_1G_PryArray))
#define yAddr_z_HANmessages_1G_PryArray(V1,V2) ((z_HANmessages_1J_DevPriority *)GenGArray_Modify((xGArray_Type *)V1,V2,&ySDL_z_HANmessages_1G_PryArray))
#ifndef ANY_z_HANmessages_1G_PryArray
#define ANY_z_HANmessages_1G_PryArray(R) (z_HANmessages_1G_PryArray *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_HANmessages_1G_PryArray)
#endif
#define z_HANmessages_1G6_copy(P,R)  (P)

/*****
* SYNTYPE Charge  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),30,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1K_Charge;
#define ySrtN_z_HANmessages_1K_Charge  (&ySrtR_z_HANmessages_1K_Charge)
#endif

#define yAssF_z_HANmessages_1K_Charge(V,E,A)  yAssF_SDL_Real(V,E,A)
#define yEqF_z_HANmessages_1K_Charge(Expr1,Expr2)  yEqF_SDL_Real(Expr1,Expr2)
#define yNEqF_z_HANmessages_1K_Charge(Expr1,Expr2)  yNEqF_SDL_Real(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1K_Charge(Expr1,Expr2) yMkAddr_SDL_Real(yTstA_z_HANmessages_1K_Charge(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1K_Charge (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1K_Charge yTstA_z_HANmessages_1K_Charge
  (z_HANmessages_1K_Charge yExpr);
#else
#define yTstA_z_HANmessages_1K_Charge(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1K_Charge
#define ANY_z_HANmessages_1K_Charge ANY_for_syntype_Charge_not_implemented
#endif

/*****
* SYNTYPE Consumption  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),2,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1L_Consumption;
#define ySrtN_z_HANmessages_1L_Consumption  (&ySrtR_z_HANmessages_1L_Consumption)
#endif

#define yAssF_z_HANmessages_1L_Consumption(V,E,A)  yAssF_SDL_Real(V,E,A)
#define yEqF_z_HANmessages_1L_Consumption(Expr1,Expr2)  yEqF_SDL_Real(Expr1,Expr2)
#define yNEqF_z_HANmessages_1L_Consumption(Expr1,Expr2)  yNEqF_SDL_Real(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1L_Consumption(Expr1,Expr2) yMkAddr_SDL_Real(yTstA_z_HANmessages_1L_Consumption(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1L_Consumption (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1L_Consumption yTstA_z_HANmessages_1L_Consumption
  (z_HANmessages_1L_Consumption yExpr);
#else
#define yTstA_z_HANmessages_1L_Consumption(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1L_Consumption
#define ANY_z_HANmessages_1L_Consumption ANY_for_syntype_Consumption_not_implemented
#endif

/*****
* SYNTYPE FULL  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),6,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1M_FULL;
#define ySrtN_z_HANmessages_1M_FULL  (&ySrtR_z_HANmessages_1M_FULL)
#endif

#define yAssF_z_HANmessages_1M_FULL(V,E,A)  yAssF_SDL_Real(V,E,A)
#define yEqF_z_HANmessages_1M_FULL(Expr1,Expr2)  yEqF_SDL_Real(Expr1,Expr2)
#define yNEqF_z_HANmessages_1M_FULL(Expr1,Expr2)  yNEqF_SDL_Real(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1M_FULL(Expr1,Expr2) yMkAddr_SDL_Real(yTstA_z_HANmessages_1M_FULL(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1M_FULL (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1M_FULL yTstA_z_HANmessages_1M_FULL
  (z_HANmessages_1M_FULL yExpr);
#else
#define yTstA_z_HANmessages_1M_FULL(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1M_FULL
#define ANY_z_HANmessages_1M_FULL ANY_for_syntype_FULL_not_implemented
#endif

/*****
* SYNTYPE Price  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),10,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1N_Price;
#define ySrtN_z_HANmessages_1N_Price  (&ySrtR_z_HANmessages_1N_Price)
#endif

#define yAssF_z_HANmessages_1N_Price(V,E,A)  yAssF_SDL_Real(V,E,A)
#define yEqF_z_HANmessages_1N_Price(Expr1,Expr2)  yEqF_SDL_Real(Expr1,Expr2)
#define yNEqF_z_HANmessages_1N_Price(Expr1,Expr2)  yNEqF_SDL_Real(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1N_Price(Expr1,Expr2) yMkAddr_SDL_Real(yTstA_z_HANmessages_1N_Price(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1N_Price (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1N_Price yTstA_z_HANmessages_1N_Price
  (z_HANmessages_1N_Price yExpr);
#else
#define yTstA_z_HANmessages_1N_Price(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1N_Price
#define ANY_z_HANmessages_1N_Price ANY_for_syntype_Price_not_implemented
#endif

/*****
* SYNTYPE Storage  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),14,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1O_Storage;
#define ySrtN_z_HANmessages_1O_Storage  (&ySrtR_z_HANmessages_1O_Storage)
#endif

#define yAssF_z_HANmessages_1O_Storage(V,E,A)  yAssF_SDL_Real(V,E,A)
#define yEqF_z_HANmessages_1O_Storage(Expr1,Expr2)  yEqF_SDL_Real(Expr1,Expr2)
#define yNEqF_z_HANmessages_1O_Storage(Expr1,Expr2)  yNEqF_SDL_Real(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1O_Storage(Expr1,Expr2) yMkAddr_SDL_Real(yTstA_z_HANmessages_1O_Storage(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1O_Storage (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1O_Storage yTstA_z_HANmessages_1O_Storage
  (z_HANmessages_1O_Storage yExpr);
#else
#define yTstA_z_HANmessages_1O_Storage(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1O_Storage
#define ANY_z_HANmessages_1O_Storage ANY_for_syntype_Storage_not_implemented
#endif

/*****
* SYNTYPE BidID  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),18,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1P_BidID;
#define ySrtN_z_HANmessages_1P_BidID  (&ySrtR_z_HANmessages_1P_BidID)
#endif

#define yAssF_z_HANmessages_1P_BidID(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_HANmessages_1P_BidID(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_HANmessages_1P_BidID(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1P_BidID(Expr1,Expr2) yMkAddr_SDL_Integer(yTstA_z_HANmessages_1P_BidID(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1P_BidID (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1P_BidID yTstA_z_HANmessages_1P_BidID
  (z_HANmessages_1P_BidID yExpr);
#else
#define yTstA_z_HANmessages_1P_BidID(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1P_BidID
#define ANY_z_HANmessages_1P_BidID ANY_for_syntype_BidID_not_implemented
#endif

/*****
* SYNTYPE RTPID  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),22,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1Q_RTPID;
#define ySrtN_z_HANmessages_1Q_RTPID  (&ySrtR_z_HANmessages_1Q_RTPID)
#endif

#define yAssF_z_HANmessages_1Q_RTPID(V,E,A)  yAssF_SDL_Integer(V,E,A)
#define yEqF_z_HANmessages_1Q_RTPID(Expr1,Expr2)  yEqF_SDL_Integer(Expr1,Expr2)
#define yNEqF_z_HANmessages_1Q_RTPID(Expr1,Expr2)  yNEqF_SDL_Integer(Expr1,Expr2)
#define yMkAddr_z_HANmessages_1Q_RTPID(Expr1,Expr2) yMkAddr_SDL_Integer(yTstA_z_HANmessages_1Q_RTPID(Expr1),Expr2)
#ifdef XTESTF
extern xbool  yTest_z_HANmessages_1Q_RTPID (void *yExpr);
#endif
#ifdef XERANGE
extern z_HANmessages_1Q_RTPID yTstA_z_HANmessages_1Q_RTPID
  (z_HANmessages_1Q_RTPID yExpr);
#else
#define yTstA_z_HANmessages_1Q_RTPID(yExpr)  (yExpr)
#endif
#ifndef ANY_z_HANmessages_1Q_RTPID
#define ANY_z_HANmessages_1Q_RTPID ANY_for_syntype_RTPID_not_implemented
#endif

/*****
* NEWTYPE SetID  (HEADING section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),26,2)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z_HANmessages_1H_SetID;
#define ySrtN_z_HANmessages_1H_SetID  (&ySrtR_z_HANmessages_1H_SetID)
#endif

#define yEmpty_z_HANmessages_1H_SetID(Result) GenBag_Empty(&ySDL_z_HANmessages_1H_SetID,Result)
#define yMakebag_z_HANmessages_1H_SetID(P1,Result) GenBag_Makebag((void *)P1,&ySDL_z_HANmessages_1H_SetID,(xBag_Type *)Result)
#define yIn_z_HANmessages_1H_SetID(P1,P2) GenBag_In((void *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID)
#define yIncl_z_HANmessages_1H_SetID(P1,P2,Result) GenBag_Incl((void *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID,(xBag_Type *)Result)
#define yDel_z_HANmessages_1H_SetID(P1,P2,Result) GenBag_Del((void *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID,(xBag_Type *)Result)
#define yIncl2_z_HANmessages_1H_SetID(P1,P2) GenBag_Incl2((void *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID)
#define yDel2_z_HANmessages_1H_SetID(P1,P2) GenBag_Del2((void *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID)
#define yLT_z_HANmessages_1H_SetID(P1,P2) GenBag_LT((xBag_Type *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID)
#define yLE_z_HANmessages_1H_SetID(P1,P2) GenBag_LE((xBag_Type *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID)
#define yGT_z_HANmessages_1H_SetID(P1,P2) yLT_z_HANmessages_1H_SetID(P2,P1)
#define yGE_z_HANmessages_1H_SetID(P1,P2)  yLE_z_HANmessages_1H_SetID(P2,P1)
#define yAnd_z_HANmessages_1H_SetID(P1,P2,Result) GenBag_And((xBag_Type *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID,(xBag_Type *)Result)
#define yOr_z_HANmessages_1H_SetID(P1,P2,Result) GenBag_Or((xBag_Type *)P1,(xBag_Type *)P2,&ySDL_z_HANmessages_1H_SetID,(xBag_Type *)Result)
#define yLength_z_HANmessages_1H_SetID(P1) GenBag_Length((xBag_Type *)P1,&ySDL_z_HANmessages_1H_SetID)
#define yTake_z_HANmessages_1H_SetID(P1,Result) (z_HANmessages_1I_AppID*)GenBag_Take((xBag_Type *)P1,&ySDL_z_HANmessages_1H_SetID,(void *)Result)
#define yTake2_z_HANmessages_1H_SetID(P1,P2,Result) (z_HANmessages_1I_AppID*)GenBag_Take2((xBag_Type *)P1,(SDL_Integer)P2,&ySDL_z_HANmessages_1H_SetID,(void *)Result)

#define yAss_z_HANmessages_1H_SetID(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z_HANmessages_1H_SetID)
#define yAssF_z_HANmessages_1H_SetID(V,E,A)  yAss_z_HANmessages_1H_SetID(&(V),E,A)
#define yEq_z_HANmessages_1H_SetID(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z_HANmessages_1H_SetID)
#define yEqF_z_HANmessages_1H_SetID(Expr1,Expr2)  yEq_z_HANmessages_1H_SetID(Expr1,Expr2)
#define yNEqF_z_HANmessages_1H_SetID(Expr1,Expr2)  ( !( yEq_z_HANmessages_1H_SetID(Expr1,Expr2)) )
#define yFree_z_HANmessages_1H_SetID(P) GenericFreeSort((void **)(P), (tSDLTypeInfo *)&ySDL_z_HANmessages_1H_SetID)
#ifndef ANY_z_HANmessages_1H_SetID
#define ANY_z_HANmessages_1H_SetID(R) (z_HANmessages_1H_SetID *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z_HANmessages_1H_SetID)
#endif
#define z_HANmessages_1HJ_copy(P,R)  (P)
#define z_HANmessages_1H0_empty  yEmpty_z_HANmessages_1H_SetID

/*****
* SIGNAL PowerON
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),2,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_00_PowerON;
#define ySigN_z_HANmessages_00_PowerON  (&ySigR_z_HANmessages_00_PowerON)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1I_AppID  Param1;
    z_HANmessages_1C_AppType  Param2;
    z_HANmessages_1J_DevPriority  Param3;
    z_HANmessages_1L_Consumption  Param4;
} yPDef_z_HANmessages_00_PowerON;
typedef yPDef_z_HANmessages_00_PowerON  *yPDP_z_HANmessages_00_PowerON;

/*****
* SIGNAL PowerOFF
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),3,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_01_PowerOFF;
#define ySigN_z_HANmessages_01_PowerOFF  (&ySigR_z_HANmessages_01_PowerOFF)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1I_AppID  Param1;
} yPDef_z_HANmessages_01_PowerOFF;
typedef yPDef_z_HANmessages_01_PowerOFF  *yPDP_z_HANmessages_01_PowerOFF;

/*****
* SIGNAL Register
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),4,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_02_Register;
#define ySigN_z_HANmessages_02_Register  (&ySigR_z_HANmessages_02_Register)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1I_AppID  Param1;
    z_HANmessages_1C_AppType  Param2;
    z_HANmessages_1J_DevPriority  Param3;
} yPDef_z_HANmessages_02_Register;
typedef yPDef_z_HANmessages_02_Register  *yPDP_z_HANmessages_02_Register;

/*****
* SIGNAL RegisterOK
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),5,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_03_RegisterOK;
#define ySigN_z_HANmessages_03_RegisterOK  (&ySigR_z_HANmessages_03_RegisterOK)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1I_AppID  Param1;
} yPDef_z_HANmessages_03_RegisterOK;
typedef yPDef_z_HANmessages_03_RegisterOK  *yPDP_z_HANmessages_03_RegisterOK;

/*****
* SIGNAL AddDevice
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),6,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_04_AddDevice;
#define ySigN_z_HANmessages_04_AddDevice  (&ySigR_z_HANmessages_04_AddDevice)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1I_AppID  Param1;
    z_HANmessages_1C_AppType  Param2;
    SDL_PId  Param3;
    z_HANmessages_1J_DevPriority  Param4;
} yPDef_z_HANmessages_04_AddDevice;
typedef yPDef_z_HANmessages_04_AddDevice  *yPDP_z_HANmessages_04_AddDevice;

/*****
* SIGNAL Unregister
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),7,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_05_Unregister;
#define ySigN_z_HANmessages_05_Unregister  (&ySigR_z_HANmessages_05_Unregister)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1I_AppID  Param1;
} yPDef_z_HANmessages_05_Unregister;
typedef yPDef_z_HANmessages_05_Unregister  *yPDP_z_HANmessages_05_Unregister;

/*****
* SIGNAL DeleteDev
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),8,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_06_DeleteDev;
#define ySigN_z_HANmessages_06_DeleteDev  (&ySigR_z_HANmessages_06_DeleteDev)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1I_AppID  Param1;
} yPDef_z_HANmessages_06_DeleteDev;
typedef yPDef_z_HANmessages_06_DeleteDev  *yPDP_z_HANmessages_06_DeleteDev;

/*****
* SIGNAL ConnectEV
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),9,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_07_ConnectEV;
#define ySigN_z_HANmessages_07_ConnectEV  (&ySigR_z_HANmessages_07_ConnectEV)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1K_Charge  Param1;
    z_HANmessages_1L_Consumption  Param2;
    z_HANmessages_1M_FULL  Param3;
} yPDef_z_HANmessages_07_ConnectEV;
typedef yPDef_z_HANmessages_07_ConnectEV  *yPDP_z_HANmessages_07_ConnectEV;

/*****
* SIGNAL DisconnectEV
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),10,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_08_DisconnectEV;
#define ySigN_z_HANmessages_08_DisconnectEV  (&ySigR_z_HANmessages_08_DisconnectEV)

/*****
* SIGNAL RegisterEV
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),11,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_09_RegisterEV;
#define ySigN_z_HANmessages_09_RegisterEV  (&ySigR_z_HANmessages_09_RegisterEV)

/*****
* SIGNAL RegisterEVOK
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),12,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0A_RegisterEVOK;
#define ySigN_z_HANmessages_0A_RegisterEVOK  (&ySigR_z_HANmessages_0A_RegisterEVOK)

/*****
* SIGNAL UnregisterEV
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),13,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0B_UnregisterEV;
#define ySigN_z_HANmessages_0B_UnregisterEV  (&ySigR_z_HANmessages_0B_UnregisterEV)

/*****
* SIGNAL EVready
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),14,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0C_EVready;
#define ySigN_z_HANmessages_0C_EVready  (&ySigR_z_HANmessages_0C_EVready)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1K_Charge  Param1;
} yPDef_z_HANmessages_0C_EVready;
typedef yPDef_z_HANmessages_0C_EVready  *yPDP_z_HANmessages_0C_EVready;

/*****
* SIGNAL ChargeCar
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),15,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0D_ChargeCar;
#define ySigN_z_HANmessages_0D_ChargeCar  (&ySigR_z_HANmessages_0D_ChargeCar)

/*****
* SIGNAL RevisedBatt
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),16,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0E_RevisedBatt;
#define ySigN_z_HANmessages_0E_RevisedBatt  (&ySigR_z_HANmessages_0E_RevisedBatt)
typedef struct {
    SIGNAL_VARS
    SDL_Boolean  Param1;
} yPDef_z_HANmessages_0E_RevisedBatt;
typedef yPDef_z_HANmessages_0E_RevisedBatt  *yPDP_z_HANmessages_0E_RevisedBatt;

/*****
* SIGNAL MeteringData
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),17,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0F_MeteringData;
#define ySigN_z_HANmessages_0F_MeteringData  (&ySigR_z_HANmessages_0F_MeteringData)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1L_Consumption  Param1;
} yPDef_z_HANmessages_0F_MeteringData;
typedef yPDef_z_HANmessages_0F_MeteringData  *yPDP_z_HANmessages_0F_MeteringData;

/*****
* SIGNAL MeteringSum
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),18,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0G_MeteringSum;
#define ySigN_z_HANmessages_0G_MeteringSum  (&ySigR_z_HANmessages_0G_MeteringSum)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1L_Consumption  Param1;
} yPDef_z_HANmessages_0G_MeteringSum;
typedef yPDef_z_HANmessages_0G_MeteringSum  *yPDP_z_HANmessages_0G_MeteringSum;

/*****
* SIGNAL ApproxBilling
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),19,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0H_ApproxBilling;
#define ySigN_z_HANmessages_0H_ApproxBilling  (&ySigR_z_HANmessages_0H_ApproxBilling)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1N_Price  Param1;
} yPDef_z_HANmessages_0H_ApproxBilling;
typedef yPDef_z_HANmessages_0H_ApproxBilling  *yPDP_z_HANmessages_0H_ApproxBilling;

/*****
* SIGNAL getMetering
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),20,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0I_getMetering;
#define ySigN_z_HANmessages_0I_getMetering  (&ySigR_z_HANmessages_0I_getMetering)

/*****
* SIGNAL SendMetering
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),21,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0J_SendMetering;
#define ySigN_z_HANmessages_0J_SendMetering  (&ySigR_z_HANmessages_0J_SendMetering)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1L_Consumption  Param1;
} yPDef_z_HANmessages_0J_SendMetering;
typedef yPDef_z_HANmessages_0J_SendMetering  *yPDP_z_HANmessages_0J_SendMetering;

/*****
* SIGNAL RenewableE
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),22,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0K_RenewableE;
#define ySigN_z_HANmessages_0K_RenewableE  (&ySigR_z_HANmessages_0K_RenewableE)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1O_Storage  Param1;
    SDL_Duration  Param2;
} yPDef_z_HANmessages_0K_RenewableE;
typedef yPDef_z_HANmessages_0K_RenewableE  *yPDP_z_HANmessages_0K_RenewableE;

/*****
* SIGNAL UseStorage
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),23,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0L_UseStorage;
#define ySigN_z_HANmessages_0L_UseStorage  (&ySigR_z_HANmessages_0L_UseStorage)
typedef struct {
    SIGNAL_VARS
    SDL_Boolean  Param1;
} yPDef_z_HANmessages_0L_UseStorage;
typedef yPDef_z_HANmessages_0L_UseStorage  *yPDP_z_HANmessages_0L_UseStorage;

/*****
* SIGNAL ResetCost
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),24,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0M_ResetCost;
#define ySigN_z_HANmessages_0M_ResetCost  (&ySigR_z_HANmessages_0M_ResetCost)

/*****
* SIGNAL Bid
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),25,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0N_Bid;
#define ySigN_z_HANmessages_0N_Bid  (&ySigR_z_HANmessages_0N_Bid)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1P_BidID  Param1;
    z_HANmessages_1L_Consumption  Param2;
    z_HANmessages_1N_Price  Param3;
} yPDef_z_HANmessages_0N_Bid;
typedef yPDef_z_HANmessages_0N_Bid  *yPDP_z_HANmessages_0N_Bid;

/*****
* SIGNAL AcceptBid
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),26,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0O_AcceptBid;
#define ySigN_z_HANmessages_0O_AcceptBid  (&ySigR_z_HANmessages_0O_AcceptBid)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1P_BidID  Param1;
    SDL_Boolean  Param2;
} yPDef_z_HANmessages_0O_AcceptBid;
typedef yPDef_z_HANmessages_0O_AcceptBid  *yPDP_z_HANmessages_0O_AcceptBid;

/*****
* SIGNAL SaleEnergy
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),27,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0P_SaleEnergy;
#define ySigN_z_HANmessages_0P_SaleEnergy  (&ySigR_z_HANmessages_0P_SaleEnergy)
typedef struct {
    SIGNAL_VARS
    SDL_Boolean  Param1;
    z_HANmessages_1N_Price  Param2;
} yPDef_z_HANmessages_0P_SaleEnergy;
typedef yPDef_z_HANmessages_0P_SaleEnergy  *yPDP_z_HANmessages_0P_SaleEnergy;

/*****
* SIGNAL BidAccepted
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),28,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0Q_BidAccepted;
#define ySigN_z_HANmessages_0Q_BidAccepted  (&ySigR_z_HANmessages_0Q_BidAccepted)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1P_BidID  Param1;
} yPDef_z_HANmessages_0Q_BidAccepted;
typedef yPDef_z_HANmessages_0Q_BidAccepted  *yPDP_z_HANmessages_0Q_BidAccepted;

/*****
* SIGNAL BidRefused
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),29,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0R_BidRefused;
#define ySigN_z_HANmessages_0R_BidRefused  (&ySigR_z_HANmessages_0R_BidRefused)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1P_BidID  Param1;
} yPDef_z_HANmessages_0R_BidRefused;
typedef yPDef_z_HANmessages_0R_BidRefused  *yPDP_z_HANmessages_0R_BidRefused;

/*****
* SIGNAL getBatteryCharge
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),30,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0S_getBatteryCharge;
#define ySigN_z_HANmessages_0S_getBatteryCharge  (&ySigR_z_HANmessages_0S_getBatteryCharge)

/*****
* SIGNAL SendBatteryCharge
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),31,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0T_SendBatteryCharge;
#define ySigN_z_HANmessages_0T_SendBatteryCharge  (&ySigR_z_HANmessages_0T_SendBatteryCharge)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1L_Consumption  Param1;
} yPDef_z_HANmessages_0T_SendBatteryCharge;
typedef yPDef_z_HANmessages_0T_SendBatteryCharge  *yPDP_z_HANmessages_0T_SendBatteryCharge;

/*****
* SIGNAL ReviseBattery
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),32,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0U_ReviseBattery;
#define ySigN_z_HANmessages_0U_ReviseBattery  (&ySigR_z_HANmessages_0U_ReviseBattery)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1L_Consumption  Param1;
} yPDef_z_HANmessages_0U_ReviseBattery;
typedef yPDef_z_HANmessages_0U_ReviseBattery  *yPDP_z_HANmessages_0U_ReviseBattery;

/*****
* SIGNAL RTP
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),33,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0V_RTP;
#define ySigN_z_HANmessages_0V_RTP  (&ySigR_z_HANmessages_0V_RTP)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1Q_RTPID  Param1;
    z_HANmessages_1L_Consumption  Param2;
    SDL_Duration  Param3;
    z_HANmessages_1N_Price  Param4;
} yPDef_z_HANmessages_0V_RTP;
typedef yPDef_z_HANmessages_0V_RTP  *yPDP_z_HANmessages_0V_RTP;

/*****
* SIGNAL AcceptRTP
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),34,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0W_AcceptRTP;
#define ySigN_z_HANmessages_0W_AcceptRTP  (&ySigR_z_HANmessages_0W_AcceptRTP)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1Q_RTPID  Param1;
    SDL_Boolean  Param2;
} yPDef_z_HANmessages_0W_AcceptRTP;
typedef yPDef_z_HANmessages_0W_AcceptRTP  *yPDP_z_HANmessages_0W_AcceptRTP;

/*****
* SIGNAL RTPAccepted
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),35,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0X_RTPAccepted;
#define ySigN_z_HANmessages_0X_RTPAccepted  (&ySigR_z_HANmessages_0X_RTPAccepted)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1Q_RTPID  Param1;
} yPDef_z_HANmessages_0X_RTPAccepted;
typedef yPDef_z_HANmessages_0X_RTPAccepted  *yPDP_z_HANmessages_0X_RTPAccepted;

/*****
* SIGNAL RTPRefused
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),36,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0Y_RTPRefused;
#define ySigN_z_HANmessages_0Y_RTPRefused  (&ySigR_z_HANmessages_0Y_RTPRefused)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1Q_RTPID  Param1;
} yPDef_z_HANmessages_0Y_RTPRefused;
typedef yPDef_z_HANmessages_0Y_RTPRefused  *yPDP_z_HANmessages_0Y_RTPRefused;

/*****
* SIGNAL Shutdown
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),37,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z_HANmessages_0Z_Shutdown;
#define ySigN_z_HANmessages_0Z_Shutdown  (&ySigR_z_HANmessages_0Z_Shutdown)
typedef struct {
    SIGNAL_VARS
    z_HANmessages_1I_AppID  Param1;
} yPDef_z_HANmessages_0Z_Shutdown;
typedef yPDef_z_HANmessages_0Z_Shutdown  *yPDP_z_HANmessages_0Z_Shutdown;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/
#endif
