
/* Program generated by Cbasic 6.2.0 9879 */
#define XSCT_CBASIC

#define SCT_VERSION_6_2
#define XENABLE_VERSION_CHECK

#include "scttypes.h"
#include "HANmessages.h"
#ifdef XINCLUDE_HS_FILE
#include "HAN.hs"
#endif
#ifdef XCTRACE
static char  xFileName[] = "C:\\Users\\ZAHID\\Desktop\\HAN_v3\\organizer\\HANmessages.c";
#endif


/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* PACKAGE HANmessages
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun,4,1,9)
******/
XCONST struct xPackageIdStruct yPacR_z_HANmessages__HANmessages = {xPackageEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&xSymbolTableIdRec, "HANmessages"
  XCOMMON_EXTRAS xIdNames(0) XPAC_EXTRAS};

/*****
* SYNTYPE AppID  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),2,2)
******/

/* *** AppID *** */
#ifndef XTNOUSE_AppID
tSDLGenInfo ySDL_z_HANmessages_1I_AppID = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1I_AppID) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("AppID") xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1I_AppID), (tSDLTypeInfo *)&ySDL_SDL_Integer};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1I_AppID = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "AppID"
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(yTest_z_HANmessages_1I_AppID),
  (xptrint)sizeof(z_HANmessages_1I_AppID), xSyntype, &xSrtR_SDL_Integer,
  &xSrtR_SDL_Integer, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1I_AppID(void * yExpr)
{
  {
    if (xGT_SDL_Integer(*(z_HANmessages_1I_AppID *)yExpr, 0)) {
      return (xbool)1;
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1I_AppID yTstA_z_HANmessages_1I_AppID
  (z_HANmessages_1I_AppID yExpr)
{
  if (! (yTest_z_HANmessages_1I_AppID((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE AppType  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),5,9)
******/

/* *** AppType *** */
#ifndef XTNOUSE_AppType
#ifdef XREADANDWRITEF
tSDLEnumLiteralInfo fSDL_z_HANmessages_1C_AppType[] = {
     {(int)z_HANmessages_1C0_CTRL, "CTRL"}, {(int)z_HANmessages_1C1_CRITICAL,
    "CRITICAL"}, {(int)z_HANmessages_1C2_NULL, "NULL"} };
#endif
tSDLEnumInfo ySDL_z_HANmessages_1C_AppType = {type_SDL_Enum, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1C_AppType) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("AppType")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1C_AppType), 0 xRaWF(3)
  xRaWF(fSDL_z_HANmessages_1C_AppType)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1C_AppType = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "AppType"
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(0),
  (xptrint)sizeof(z_HANmessages_1C_AppType), xEnum, (xSortIdNode)0,
  (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1C_AppType) XSRT_EXTRAS};
#endif
#ifndef XOPTLIT
/*-----------------LITERALS-----------------*/
static XCONST struct xLiteralIdStruct yLitR_z_HANmessages_1C0_CTRL =
  {xLiteralEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&ySrtR_z_HANmessages_1C_AppType, "CTRL" XCOMMON_EXTRAS,
  (int)z_HANmessages_1C0_CTRL XLIT_EXTRAS};
static XCONST struct xLiteralIdStruct yLitR_z_HANmessages_1C1_CRITICAL =
  {xLiteralEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&ySrtR_z_HANmessages_1C_AppType, "CRITICAL" XCOMMON_EXTRAS,
  (int)z_HANmessages_1C1_CRITICAL XLIT_EXTRAS};
static XCONST struct xLiteralIdStruct yLitR_z_HANmessages_1C2_NULL =
  {xLiteralEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&ySrtR_z_HANmessages_1C_AppType, "NULL" XCOMMON_EXTRAS,
  (int)z_HANmessages_1C2_NULL XLIT_EXTRAS};
#endif

/*****
* SYNTYPE DevPriority  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),10,2)
******/

/* *** DevPriority *** */
#ifndef XTNOUSE_DevPriority
tSDLGenInfo ySDL_z_HANmessages_1J_DevPriority = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1J_DevPriority) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("DevPriority")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1J_DevPriority),
  (tSDLTypeInfo *)&ySDL_SDL_Integer};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1J_DevPriority = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "DevPriority" XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(yTest_z_HANmessages_1J_DevPriority),
  (xptrint)sizeof(z_HANmessages_1J_DevPriority), xSyntype, &xSrtR_SDL_Integer,
  &xSrtR_SDL_Integer, 0, 2, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1J_DevPriority) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1J_DevPriority(void * yExpr)
{
  {
    if (xLE_SDL_Integer(0, *(z_HANmessages_1J_DevPriority *)yExpr)) {
      if (xLE_SDL_Integer(*(z_HANmessages_1J_DevPriority *)yExpr, 2)) {
        return (xbool)1;
      }
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1J_DevPriority yTstA_z_HANmessages_1J_DevPriority
  (z_HANmessages_1J_DevPriority yExpr)
{
  if (! (yTest_z_HANmessages_1J_DevPriority((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1J_DevPriority,
  (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE AppArray  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),14,2)
******/

/* *** AppArray *** */
#ifndef XTNOUSE_AppArray
tSDLGArrayInfo ySDL_z_HANmessages_1D_AppArray = {type_SDL_GArray, 15,
  (T_SORTSIZE)sizeof(z_HANmessages_1D_AppArray) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("AppArray")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1D_AppArray),
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID, (tSDLTypeInfo *)&ySDL_SDL_PId,
  (T_SORTSIZE)sizeof(z_HANmessages_1D_AppArray_yrec), xOffsetOf(
  z_HANmessages_1D_AppArray_yrec, Index), xOffsetOf(
  z_HANmessages_1D_AppArray_yrec, Data), xOffsetOf(
  z_HANmessages_1D_AppArray, Data)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1D_AppArray = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "AppArray" XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_HANmessages_1D_AppArray)
  xEqF(yEq_z_HANmessages_1D_AppArray) xTestF(0),
  (xptrint)sizeof(z_HANmessages_1D_AppArray), xGArray, &xSrtR_SDL_PId,
  &ySrtR_z_HANmessages_1I_AppID, (long int)xOffsetOf(
  z_HANmessages_1D_AppArray_yrec, Data), (long int)sizeof(
  z_HANmessages_1D_AppArray_yrec), (long int)xOffsetOf(
  z_HANmessages_1D_AppArray_yrec, Index), (long int)xOffsetOf(
  z_HANmessages_1D_AppArray, Data)
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1D_AppArray) XSRT_EXTRAS};
#endif

/*****
* NEWTYPE TypeArray  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),18,2)
******/

/* *** TypeArray *** */
#ifndef XTNOUSE_TypeArray
tSDLGArrayInfo ySDL_z_HANmessages_1E_TypeArray = {type_SDL_GArray, 15,
  (T_SORTSIZE)sizeof(z_HANmessages_1E_TypeArray) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("TypeArray")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1E_TypeArray),
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1C_AppType, (T_SORTSIZE)sizeof(
  z_HANmessages_1E_TypeArray_yrec), xOffsetOf(
  z_HANmessages_1E_TypeArray_yrec, Index), xOffsetOf(
  z_HANmessages_1E_TypeArray_yrec, Data), xOffsetOf(
  z_HANmessages_1E_TypeArray, Data)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1E_TypeArray = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "TypeArray" XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_HANmessages_1E_TypeArray)
  xEqF(yEq_z_HANmessages_1E_TypeArray) xTestF(0),
  (xptrint)sizeof(z_HANmessages_1E_TypeArray), xGArray,
  &ySrtR_z_HANmessages_1C_AppType, &ySrtR_z_HANmessages_1I_AppID,
  (long int)xOffsetOf(z_HANmessages_1E_TypeArray_yrec, Data), (long int)sizeof(
  z_HANmessages_1E_TypeArray_yrec), (long int)xOffsetOf(
  z_HANmessages_1E_TypeArray_yrec, Index), (long int)xOffsetOf(
  z_HANmessages_1E_TypeArray, Data)
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1E_TypeArray) XSRT_EXTRAS};
#endif

/*****
* NEWTYPE ConsArray  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),22,2)
******/

/* *** ConsArray *** */
#ifndef XTNOUSE_ConsArray
tSDLGArrayInfo ySDL_z_HANmessages_1F_ConsArray = {type_SDL_GArray, 15,
  (T_SORTSIZE)sizeof(z_HANmessages_1F_ConsArray) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("ConsArray")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1F_ConsArray),
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption, (T_SORTSIZE)sizeof(
  z_HANmessages_1F_ConsArray_yrec), xOffsetOf(
  z_HANmessages_1F_ConsArray_yrec, Index), xOffsetOf(
  z_HANmessages_1F_ConsArray_yrec, Data), xOffsetOf(
  z_HANmessages_1F_ConsArray, Data)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1F_ConsArray = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "ConsArray" XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_HANmessages_1F_ConsArray)
  xEqF(yEq_z_HANmessages_1F_ConsArray) xTestF(0),
  (xptrint)sizeof(z_HANmessages_1F_ConsArray), xGArray,
  &ySrtR_z_HANmessages_1L_Consumption, &ySrtR_z_HANmessages_1I_AppID,
  (long int)xOffsetOf(z_HANmessages_1F_ConsArray_yrec, Data), (long int)sizeof(
  z_HANmessages_1F_ConsArray_yrec), (long int)xOffsetOf(
  z_HANmessages_1F_ConsArray_yrec, Index), (long int)xOffsetOf(
  z_HANmessages_1F_ConsArray, Data)
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1F_ConsArray) XSRT_EXTRAS};
#endif

/*****
* NEWTYPE PryArray  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),26,2)
******/

/* *** PryArray *** */
#ifndef XTNOUSE_PryArray
tSDLGArrayInfo ySDL_z_HANmessages_1G_PryArray = {type_SDL_GArray, 15,
  (T_SORTSIZE)sizeof(z_HANmessages_1G_PryArray) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("PryArray")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1G_PryArray),
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1J_DevPriority, (T_SORTSIZE)sizeof(
  z_HANmessages_1G_PryArray_yrec), xOffsetOf(
  z_HANmessages_1G_PryArray_yrec, Index), xOffsetOf(
  z_HANmessages_1G_PryArray_yrec, Data), xOffsetOf(
  z_HANmessages_1G_PryArray, Data)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1G_PryArray = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "PryArray" XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_HANmessages_1G_PryArray)
  xEqF(yEq_z_HANmessages_1G_PryArray) xTestF(0),
  (xptrint)sizeof(z_HANmessages_1G_PryArray), xGArray,
  &ySrtR_z_HANmessages_1J_DevPriority, &ySrtR_z_HANmessages_1I_AppID,
  (long int)xOffsetOf(z_HANmessages_1G_PryArray_yrec, Data), (long int)sizeof(
  z_HANmessages_1G_PryArray_yrec), (long int)xOffsetOf(
  z_HANmessages_1G_PryArray_yrec, Index), (long int)xOffsetOf(
  z_HANmessages_1G_PryArray, Data)
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1G_PryArray) XSRT_EXTRAS};
#endif

/*****
* SYNTYPE Charge  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),152(70,45),30,2)
******/

/* *** Charge *** */
#ifndef XTNOUSE_Charge
tSDLGenInfo ySDL_z_HANmessages_1K_Charge = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1K_Charge) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Charge")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1K_Charge), (tSDLTypeInfo *)&ySDL_SDL_Real};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1K_Charge = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "Charge"
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(yTest_z_HANmessages_1K_Charge),
  (xptrint)sizeof(z_HANmessages_1K_Charge), xSyntype, &xSrtR_SDL_Real,
  &xSrtR_SDL_Real, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1K_Charge) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1K_Charge(void * yExpr)
{
  {
    if (xLE_SDL_Real(SDL_REAL_LIT(0.0, 0, 0),
      *(z_HANmessages_1K_Charge *)yExpr)) {
      if (xLE_SDL_Real(*(z_HANmessages_1K_Charge *)yExpr,
      SDL_REAL_LIT(100.0, 100, 0))) {
        return (xbool)1;
      }
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1K_Charge yTstA_z_HANmessages_1K_Charge
  (z_HANmessages_1K_Charge yExpr)
{
  if (! (yTest_z_HANmessages_1K_Charge((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1K_Charge,
  (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* SYNTYPE Consumption  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),2,2)
******/

/* *** Consumption *** */
#ifndef XTNOUSE_Consumption
tSDLGenInfo ySDL_z_HANmessages_1L_Consumption = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1L_Consumption) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Consumption")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1L_Consumption), (tSDLTypeInfo *)&ySDL_SDL_Real};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1L_Consumption = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "Consumption" XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(yTest_z_HANmessages_1L_Consumption),
  (xptrint)sizeof(z_HANmessages_1L_Consumption), xSyntype, &xSrtR_SDL_Real,
  &xSrtR_SDL_Real, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1L_Consumption(void * yExpr)
{
  {
    if (xGE_SDL_Real(*(z_HANmessages_1L_Consumption *)yExpr,
      SDL_REAL_LIT(0.0, 0, 0))) {
      return (xbool)1;
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1L_Consumption yTstA_z_HANmessages_1L_Consumption
  (z_HANmessages_1L_Consumption yExpr)
{
  if (! (yTest_z_HANmessages_1L_Consumption((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* SYNTYPE FULL  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),6,2)
******/

/* *** FULL *** */
#ifndef XTNOUSE_FULL
tSDLGenInfo ySDL_z_HANmessages_1M_FULL = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1M_FULL) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("FULL") xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1M_FULL), (tSDLTypeInfo *)&ySDL_SDL_Real};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1M_FULL = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "FULL"
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0) xTestF(yTest_z_HANmessages_1M_FULL),
  (xptrint)sizeof(z_HANmessages_1M_FULL), xSyntype, &xSrtR_SDL_Real,
  &xSrtR_SDL_Real, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1M_FULL) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1M_FULL(void * yExpr)
{
  {
    if (xGE_SDL_Real(*(z_HANmessages_1M_FULL *)yExpr, SDL_REAL_LIT(0.0, 0, 0)))
      {
      return (xbool)1;
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1M_FULL yTstA_z_HANmessages_1M_FULL (z_HANmessages_1M_FULL yExpr)
{
  if (! (yTest_z_HANmessages_1M_FULL((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1M_FULL, (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* SYNTYPE Price  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),10,2)
******/

/* *** Price *** */
#ifndef XTNOUSE_Price
tSDLGenInfo ySDL_z_HANmessages_1N_Price = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1N_Price) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("Price") xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1N_Price), (tSDLTypeInfo *)&ySDL_SDL_Real};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1N_Price = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "Price"
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(yTest_z_HANmessages_1N_Price),
  (xptrint)sizeof(z_HANmessages_1N_Price), xSyntype, &xSrtR_SDL_Real,
  &xSrtR_SDL_Real, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1N_Price) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1N_Price(void * yExpr)
{
  {
    if (xGE_SDL_Real(*(z_HANmessages_1N_Price *)yExpr,
      SDL_REAL_LIT(0.0, 0, 0))) {
      return (xbool)1;
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1N_Price yTstA_z_HANmessages_1N_Price
  (z_HANmessages_1N_Price yExpr)
{
  if (! (yTest_z_HANmessages_1N_Price((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1N_Price,
  (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* SYNTYPE Storage  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),14,2)
******/

/* *** Storage *** */
#ifndef XTNOUSE_Storage
tSDLGenInfo ySDL_z_HANmessages_1O_Storage = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1O_Storage) T_SDL_OPFUNCS(0)
  T_SDL_EXTRA_VALUE T_SDL_Names("Storage")
  xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1O_Storage), (tSDLTypeInfo *)&ySDL_SDL_Real};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1O_Storage = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "Storage"
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(yTest_z_HANmessages_1O_Storage),
  (xptrint)sizeof(z_HANmessages_1O_Storage), xSyntype, &xSrtR_SDL_Real,
  &xSrtR_SDL_Real, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1O_Storage) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1O_Storage(void * yExpr)
{
  {
    if (xGE_SDL_Real(*(z_HANmessages_1O_Storage *)yExpr,
      SDL_REAL_LIT(0.0, 0, 0))) {
      return (xbool)1;
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1O_Storage yTstA_z_HANmessages_1O_Storage
  (z_HANmessages_1O_Storage yExpr)
{
  if (! (yTest_z_HANmessages_1O_Storage((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1O_Storage,
  (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* SYNTYPE BidID  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),18,2)
******/

/* *** BidID *** */
#ifndef XTNOUSE_BidID
tSDLGenInfo ySDL_z_HANmessages_1P_BidID = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1P_BidID) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("BidID") xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1P_BidID), (tSDLTypeInfo *)&ySDL_SDL_Integer};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1P_BidID = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "BidID"
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(yTest_z_HANmessages_1P_BidID),
  (xptrint)sizeof(z_HANmessages_1P_BidID), xSyntype, &xSrtR_SDL_Integer,
  &xSrtR_SDL_Integer, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1P_BidID) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1P_BidID(void * yExpr)
{
  {
    if (xGT_SDL_Integer(*(z_HANmessages_1P_BidID *)yExpr, 0)) {
      return (xbool)1;
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1P_BidID yTstA_z_HANmessages_1P_BidID
  (z_HANmessages_1P_BidID yExpr)
{
  if (! (yTest_z_HANmessages_1P_BidID((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1P_BidID,
  (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* SYNTYPE RTPID  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),22,2)
******/

/* *** RTPID *** */
#ifndef XTNOUSE_RTPID
tSDLGenInfo ySDL_z_HANmessages_1Q_RTPID = {type_SDL_Syntype, 0,
  (T_SORTSIZE)sizeof(z_HANmessages_1Q_RTPID) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("RTPID") xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1Q_RTPID), (tSDLTypeInfo *)&ySDL_SDL_Integer};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1Q_RTPID = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "RTPID"
  XCOMMON_EXTRAS xFreF(0) xAssF(0) xEqF(0)
  xTestF(yTest_z_HANmessages_1Q_RTPID),
  (xptrint)sizeof(z_HANmessages_1Q_RTPID), xSyntype, &xSrtR_SDL_Integer,
  &xSrtR_SDL_Integer, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1Q_RTPID) XSRT_EXTRAS};
#endif

/*-------------------TEST-------------------*/
#ifdef XTESTF
xbool yTest_z_HANmessages_1Q_RTPID(void * yExpr)
{
  {
    if (xGE_SDL_Integer(*(z_HANmessages_1Q_RTPID *)yExpr, 0)) {
      return (xbool)1;
    }
  }
  return (xbool)0;
}
#endif

/*-------------------TSTA-------------------*/
#ifdef XERANGE
z_HANmessages_1Q_RTPID yTstA_z_HANmessages_1Q_RTPID
  (z_HANmessages_1Q_RTPID yExpr)
{
  if (! (yTest_z_HANmessages_1Q_RTPID((void *)&yExpr)) ) {
    xErrorSubrange((tSDLTypeInfo *)&ySDL_z_HANmessages_1Q_RTPID,
  (void *)&yExpr);
  }
  return yExpr;
}
#endif

/*****
* NEWTYPE SetID  (BODY section)
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(1),149(145,45),26,2)
******/

/* *** SetID *** */
#ifndef XTNOUSE_SetID
tSDLGenListInfo ySDL_z_HANmessages_1H_SetID = {type_SDL_GPowerset, 15,
  (T_SORTSIZE)sizeof(z_HANmessages_1H_SetID) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("SetID") xRaWF((xIdNode)&yPacR_z_HANmessages__HANmessages)
  xRaWF(&ySrtR_z_HANmessages_1H_SetID),
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID, (T_SORTSIZE)sizeof(
  z_HANmessages_1H_SetID_yrec), xOffsetOf(z_HANmessages_1H_SetID_yrec, Data)};
#endif
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z_HANmessages_1H_SetID = {xSortEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "SetID"
  XCOMMON_EXTRAS xFreF(0) xAssF(yAss_z_HANmessages_1H_SetID)
  xEqF(yEq_z_HANmessages_1H_SetID) xTestF(0),
  (xptrint)sizeof(z_HANmessages_1H_SetID), xGPowerSet,
  &ySrtR_z_HANmessages_1I_AppID, (xSortIdNode)0, (long int)xOffsetOf(
  z_HANmessages_1H_SetID_yrec, Data), (long int)sizeof(
  z_HANmessages_1H_SetID_yrec), 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_z_HANmessages_1H_SetID) XSRT_EXTRAS};
#endif

/*****
* SIGNAL PowerON
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),2,1)
******/
static xSignalNode ySigA_z_HANmessages_00_PowerON = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_00_PowerON = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "PowerON"
  XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z_HANmessages_00_PowerON),
  &ySigA_z_HANmessages_00_PowerON, 0 xFreS(0) SIGCODE(PowerON)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),2,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_00_PowerON = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_00_PowerON
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  xOffsetOf(yPDef_z_HANmessages_00_PowerON, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_00_PowerON = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_00_PowerON
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1C_AppType,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1C_AppType,
  xOffsetOf(yPDef_z_HANmessages_00_PowerON, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR3_z_HANmessages_00_PowerON = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_00_PowerON
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1J_DevPriority,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1J_DevPriority,
  xOffsetOf(yPDef_z_HANmessages_00_PowerON, Param3), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR4_z_HANmessages_00_PowerON = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_00_PowerON
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_00_PowerON, Param4), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL PowerOFF
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),3,1)
******/
static xSignalNode ySigA_z_HANmessages_01_PowerOFF = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_01_PowerOFF = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "PowerOFF" XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z_HANmessages_01_PowerOFF),
  &ySigA_z_HANmessages_01_PowerOFF, 0 xFreS(0) SIGCODE(PowerOFF)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),3,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_01_PowerOFF = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_01_PowerOFF
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  xOffsetOf(yPDef_z_HANmessages_01_PowerOFF, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL Register
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),4,1)
******/
static xSignalNode ySigA_z_HANmessages_02_Register = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_02_Register = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "Register" XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z_HANmessages_02_Register),
  &ySigA_z_HANmessages_02_Register, 0 xFreS(0) SIGCODE(Register)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),4,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_02_Register = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_02_Register
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  xOffsetOf(yPDef_z_HANmessages_02_Register, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_02_Register = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_02_Register
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1C_AppType,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1C_AppType,
  xOffsetOf(yPDef_z_HANmessages_02_Register, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR3_z_HANmessages_02_Register = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_02_Register
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1J_DevPriority,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1J_DevPriority,
  xOffsetOf(yPDef_z_HANmessages_02_Register, Param3), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL RegisterOK
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),5,1)
******/
static xSignalNode ySigA_z_HANmessages_03_RegisterOK = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_03_RegisterOK = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "RegisterOK" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_03_RegisterOK),
  &ySigA_z_HANmessages_03_RegisterOK, 0 xFreS(0) SIGCODE(RegisterOK)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),5,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_03_RegisterOK = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_03_RegisterOK
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  xOffsetOf(yPDef_z_HANmessages_03_RegisterOK, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL AddDevice
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),6,1)
******/
static xSignalNode ySigA_z_HANmessages_04_AddDevice = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_04_AddDevice = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "AddDevice" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_04_AddDevice),
  &ySigA_z_HANmessages_04_AddDevice, 0 xFreS(0) SIGCODE(AddDevice)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),6,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_04_AddDevice = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_04_AddDevice
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  xOffsetOf(yPDef_z_HANmessages_04_AddDevice, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_04_AddDevice = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_04_AddDevice
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1C_AppType,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1C_AppType,
  xOffsetOf(yPDef_z_HANmessages_04_AddDevice, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR3_z_HANmessages_04_AddDevice = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_04_AddDevice
  xIdNames(" ") XCOMMON_EXTRAS, &xSrtR_SDL_PId, (tSDLTypeInfo *)&ySDL_SDL_PId,
  xOffsetOf(yPDef_z_HANmessages_04_AddDevice, Param3), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR4_z_HANmessages_04_AddDevice = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_04_AddDevice
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1J_DevPriority,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1J_DevPriority,
  xOffsetOf(yPDef_z_HANmessages_04_AddDevice, Param4), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL Unregister
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),7,1)
******/
static xSignalNode ySigA_z_HANmessages_05_Unregister = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_05_Unregister = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "Unregister" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_05_Unregister),
  &ySigA_z_HANmessages_05_Unregister, 0 xFreS(0) SIGCODE(Unregister)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),7,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_05_Unregister = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_05_Unregister
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  xOffsetOf(yPDef_z_HANmessages_05_Unregister, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL DeleteDev
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),8,1)
******/
static xSignalNode ySigA_z_HANmessages_06_DeleteDev = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_06_DeleteDev = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "DeleteDev" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_06_DeleteDev),
  &ySigA_z_HANmessages_06_DeleteDev, 0 xFreS(0) SIGCODE(DeleteDev)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),8,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_06_DeleteDev = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_06_DeleteDev
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  xOffsetOf(yPDef_z_HANmessages_06_DeleteDev, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL ConnectEV
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),9,1)
******/
static xSignalNode ySigA_z_HANmessages_07_ConnectEV = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_07_ConnectEV = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "ConnectEV" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_07_ConnectEV),
  &ySigA_z_HANmessages_07_ConnectEV, 0 xFreS(0) SIGCODE(ConnectEV)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),9,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_07_ConnectEV = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_07_ConnectEV
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1K_Charge,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1K_Charge,
  xOffsetOf(yPDef_z_HANmessages_07_ConnectEV, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_07_ConnectEV = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_07_ConnectEV
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_07_ConnectEV, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR3_z_HANmessages_07_ConnectEV = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_07_ConnectEV
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1M_FULL,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1M_FULL,
  xOffsetOf(yPDef_z_HANmessages_07_ConnectEV, Param3), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL DisconnectEV
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),10,1)
******/
XCONST struct xSignalIdStruct ySigR_z_HANmessages_08_DisconnectEV = {xSignalEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "DisconnectEV" XCOMMON_EXTRAS, (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0
  xFreS(0) SIGCODE(DisconnectEV)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),10,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL RegisterEV
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),11,1)
******/
XCONST struct xSignalIdStruct ySigR_z_HANmessages_09_RegisterEV = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "RegisterEV" XCOMMON_EXTRAS, (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0
  xFreS(0) SIGCODE(RegisterEV)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),11,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL RegisterEVOK
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),12,1)
******/
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0A_RegisterEVOK = {xSignalEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "RegisterEVOK" XCOMMON_EXTRAS, (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0
  xFreS(0) SIGCODE(RegisterEVOK)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),12,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL UnregisterEV
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),13,1)
******/
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0B_UnregisterEV = {xSignalEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "UnregisterEV" XCOMMON_EXTRAS, (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0
  xFreS(0) SIGCODE(UnregisterEV)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),13,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL EVready
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),14,1)
******/
static xSignalNode ySigA_z_HANmessages_0C_EVready = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0C_EVready = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "EVready"
  XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z_HANmessages_0C_EVready),
  &ySigA_z_HANmessages_0C_EVready, 0 xFreS(0) SIGCODE(EVready)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),14,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0C_EVready = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0C_EVready
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1K_Charge,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1K_Charge,
  xOffsetOf(yPDef_z_HANmessages_0C_EVready, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL ChargeCar
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),15,1)
******/
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0D_ChargeCar = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "ChargeCar" XCOMMON_EXTRAS, (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0)
  SIGCODE(ChargeCar)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),15,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL RevisedBatt
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),16,1)
******/
static xSignalNode ySigA_z_HANmessages_0E_RevisedBatt = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0E_RevisedBatt = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "RevisedBatt" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0E_RevisedBatt),
  &ySigA_z_HANmessages_0E_RevisedBatt, 0 xFreS(0) SIGCODE(RevisedBatt)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),16,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0E_RevisedBatt = {xSignalParEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0E_RevisedBatt
  xIdNames(" ") XCOMMON_EXTRAS, &xSrtR_SDL_Boolean,
  (tSDLTypeInfo *)&ySDL_SDL_Boolean,
  xOffsetOf(yPDef_z_HANmessages_0E_RevisedBatt, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL MeteringData
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),17,1)
******/
static xSignalNode ySigA_z_HANmessages_0F_MeteringData = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0F_MeteringData = {xSignalEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "MeteringData" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0F_MeteringData),
  &ySigA_z_HANmessages_0F_MeteringData, 0 xFreS(0) SIGCODE(MeteringData)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),17,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0F_MeteringData = {xSignalParEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0F_MeteringData
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_0F_MeteringData, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL MeteringSum
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),18,1)
******/
static xSignalNode ySigA_z_HANmessages_0G_MeteringSum = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0G_MeteringSum = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "MeteringSum" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0G_MeteringSum),
  &ySigA_z_HANmessages_0G_MeteringSum, 0 xFreS(0) SIGCODE(MeteringSum)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),18,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0G_MeteringSum = {xSignalParEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0G_MeteringSum
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_0G_MeteringSum, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL ApproxBilling
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),19,1)
******/
static xSignalNode ySigA_z_HANmessages_0H_ApproxBilling = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0H_ApproxBilling = {xSignalEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "ApproxBilling" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0H_ApproxBilling),
  &ySigA_z_HANmessages_0H_ApproxBilling, 0 xFreS(0) SIGCODE(ApproxBilling)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),19,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0H_ApproxBilling =
  {xSignalParEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&ySigR_z_HANmessages_0H_ApproxBilling xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_z_HANmessages_1N_Price, (tSDLTypeInfo *)&ySDL_z_HANmessages_1N_Price,
  xOffsetOf(yPDef_z_HANmessages_0H_ApproxBilling, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL getMetering
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),20,1)
******/
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0I_getMetering = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "getMetering" XCOMMON_EXTRAS, (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0
  xFreS(0) SIGCODE(getMetering)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),20,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL SendMetering
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),21,1)
******/
static xSignalNode ySigA_z_HANmessages_0J_SendMetering = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0J_SendMetering = {xSignalEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "SendMetering" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0J_SendMetering),
  &ySigA_z_HANmessages_0J_SendMetering, 0 xFreS(0) SIGCODE(SendMetering)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),21,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0J_SendMetering = {xSignalParEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0J_SendMetering
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_0J_SendMetering, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL RenewableE
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),22,1)
******/
static xSignalNode ySigA_z_HANmessages_0K_RenewableE = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0K_RenewableE = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "RenewableE" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0K_RenewableE),
  &ySigA_z_HANmessages_0K_RenewableE, 0 xFreS(0) SIGCODE(RenewableE)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),22,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0K_RenewableE = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0K_RenewableE
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1O_Storage,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1O_Storage,
  xOffsetOf(yPDef_z_HANmessages_0K_RenewableE, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_0K_RenewableE = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0K_RenewableE
  xIdNames(" ") XCOMMON_EXTRAS, &xSrtR_SDL_Duration,
  (tSDLTypeInfo *)&ySDL_SDL_Duration,
  xOffsetOf(yPDef_z_HANmessages_0K_RenewableE, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL UseStorage
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),23,1)
******/
static xSignalNode ySigA_z_HANmessages_0L_UseStorage = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0L_UseStorage = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "UseStorage" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0L_UseStorage),
  &ySigA_z_HANmessages_0L_UseStorage, 0 xFreS(0) SIGCODE(UseStorage)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),23,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0L_UseStorage = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0L_UseStorage
  xIdNames(" ") XCOMMON_EXTRAS, &xSrtR_SDL_Boolean,
  (tSDLTypeInfo *)&ySDL_SDL_Boolean,
  xOffsetOf(yPDef_z_HANmessages_0L_UseStorage, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL ResetCost
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),24,1)
******/
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0M_ResetCost = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "ResetCost" XCOMMON_EXTRAS, (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0)
  SIGCODE(ResetCost)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),24,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL Bid
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),25,1)
******/
static xSignalNode ySigA_z_HANmessages_0N_Bid = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0N_Bid = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "Bid"
  XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z_HANmessages_0N_Bid),
  &ySigA_z_HANmessages_0N_Bid, 0 xFreS(0) SIGCODE(Bid)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),25,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0N_Bid = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0N_Bid xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1P_BidID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1P_BidID,
  xOffsetOf(yPDef_z_HANmessages_0N_Bid, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_0N_Bid = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0N_Bid xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_0N_Bid, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR3_z_HANmessages_0N_Bid = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0N_Bid xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1N_Price,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1N_Price,
  xOffsetOf(yPDef_z_HANmessages_0N_Bid, Param3), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL AcceptBid
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),26,1)
******/
static xSignalNode ySigA_z_HANmessages_0O_AcceptBid = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0O_AcceptBid = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "AcceptBid" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0O_AcceptBid),
  &ySigA_z_HANmessages_0O_AcceptBid, 0 xFreS(0) SIGCODE(AcceptBid)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),26,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0O_AcceptBid = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0O_AcceptBid
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1P_BidID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1P_BidID,
  xOffsetOf(yPDef_z_HANmessages_0O_AcceptBid, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_0O_AcceptBid = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0O_AcceptBid
  xIdNames(" ") XCOMMON_EXTRAS, &xSrtR_SDL_Boolean,
  (tSDLTypeInfo *)&ySDL_SDL_Boolean,
  xOffsetOf(yPDef_z_HANmessages_0O_AcceptBid, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL SaleEnergy
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),27,1)
******/
static xSignalNode ySigA_z_HANmessages_0P_SaleEnergy = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0P_SaleEnergy = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "SaleEnergy" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0P_SaleEnergy),
  &ySigA_z_HANmessages_0P_SaleEnergy, 0 xFreS(0) SIGCODE(SaleEnergy)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),27,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0P_SaleEnergy = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0P_SaleEnergy
  xIdNames(" ") XCOMMON_EXTRAS, &xSrtR_SDL_Boolean,
  (tSDLTypeInfo *)&ySDL_SDL_Boolean,
  xOffsetOf(yPDef_z_HANmessages_0P_SaleEnergy, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_0P_SaleEnergy = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0P_SaleEnergy
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1N_Price,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1N_Price,
  xOffsetOf(yPDef_z_HANmessages_0P_SaleEnergy, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL BidAccepted
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),28,1)
******/
static xSignalNode ySigA_z_HANmessages_0Q_BidAccepted = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0Q_BidAccepted = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "BidAccepted" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0Q_BidAccepted),
  &ySigA_z_HANmessages_0Q_BidAccepted, 0 xFreS(0) SIGCODE(BidAccepted)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),28,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0Q_BidAccepted = {xSignalParEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0Q_BidAccepted
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1P_BidID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1P_BidID,
  xOffsetOf(yPDef_z_HANmessages_0Q_BidAccepted, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL BidRefused
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),29,1)
******/
static xSignalNode ySigA_z_HANmessages_0R_BidRefused = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0R_BidRefused = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "BidRefused" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0R_BidRefused),
  &ySigA_z_HANmessages_0R_BidRefused, 0 xFreS(0) SIGCODE(BidRefused)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),29,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0R_BidRefused = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0R_BidRefused
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1P_BidID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1P_BidID,
  xOffsetOf(yPDef_z_HANmessages_0R_BidRefused, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL getBatteryCharge
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),30,1)
******/
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0S_getBatteryCharge =
  {xSignalEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yPacR_z_HANmessages__HANmessages, "getBatteryCharge"
  XCOMMON_EXTRAS, (xptrint)sizeof(XSIGNALHEADERTYPE), 0, 0 xFreS(0)
  SIGCODE(getBatteryCharge)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),30,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};

/*****
* SIGNAL SendBatteryCharge
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),31,1)
******/
static xSignalNode ySigA_z_HANmessages_0T_SendBatteryCharge = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0T_SendBatteryCharge =
  {xSignalEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yPacR_z_HANmessages__HANmessages, "SendBatteryCharge"
  XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z_HANmessages_0T_SendBatteryCharge),
  &ySigA_z_HANmessages_0T_SendBatteryCharge, 0 xFreS(0)
  SIGCODE(SendBatteryCharge)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),31,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0T_SendBatteryCharge =
  {xSignalParEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&ySigR_z_HANmessages_0T_SendBatteryCharge xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_0T_SendBatteryCharge, Param1), (xptrint)0,
  (xbool)0 XSPA_EXTRAS};
#endif

/*****
* SIGNAL ReviseBattery
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),32,1)
******/
static xSignalNode ySigA_z_HANmessages_0U_ReviseBattery = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0U_ReviseBattery = {xSignalEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "ReviseBattery" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0U_ReviseBattery),
  &ySigA_z_HANmessages_0U_ReviseBattery, 0 xFreS(0) SIGCODE(ReviseBattery)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),32,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0U_ReviseBattery =
  {xSignalParEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&ySigR_z_HANmessages_0U_ReviseBattery xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_0U_ReviseBattery, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL RTP
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),33,1)
******/
static xSignalNode ySigA_z_HANmessages_0V_RTP = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0V_RTP = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages, "RTP"
  XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z_HANmessages_0V_RTP),
  &ySigA_z_HANmessages_0V_RTP, 0 xFreS(0) SIGCODE(RTP)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),33,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0V_RTP = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0V_RTP xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1Q_RTPID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1Q_RTPID,
  xOffsetOf(yPDef_z_HANmessages_0V_RTP, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_0V_RTP = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0V_RTP xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1L_Consumption,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1L_Consumption,
  xOffsetOf(yPDef_z_HANmessages_0V_RTP, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR3_z_HANmessages_0V_RTP = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0V_RTP xIdNames(" ")
  XCOMMON_EXTRAS, &xSrtR_SDL_Duration, (tSDLTypeInfo *)&ySDL_SDL_Duration,
  xOffsetOf(yPDef_z_HANmessages_0V_RTP, Param3), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR4_z_HANmessages_0V_RTP = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0V_RTP xIdNames(" ")
  XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1N_Price,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1N_Price,
  xOffsetOf(yPDef_z_HANmessages_0V_RTP, Param4), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL AcceptRTP
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),34,1)
******/
static xSignalNode ySigA_z_HANmessages_0W_AcceptRTP = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0W_AcceptRTP = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "AcceptRTP" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0W_AcceptRTP),
  &ySigA_z_HANmessages_0W_AcceptRTP, 0 xFreS(0) SIGCODE(AcceptRTP)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),34,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0W_AcceptRTP = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0W_AcceptRTP
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1Q_RTPID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1Q_RTPID,
  xOffsetOf(yPDef_z_HANmessages_0W_AcceptRTP, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
XCONST struct xVarIdStruct ySPaR2_z_HANmessages_0W_AcceptRTP = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0W_AcceptRTP
  xIdNames(" ") XCOMMON_EXTRAS, &xSrtR_SDL_Boolean,
  (tSDLTypeInfo *)&ySDL_SDL_Boolean,
  xOffsetOf(yPDef_z_HANmessages_0W_AcceptRTP, Param2), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL RTPAccepted
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),35,1)
******/
static xSignalNode ySigA_z_HANmessages_0X_RTPAccepted = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0X_RTPAccepted = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "RTPAccepted" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0X_RTPAccepted),
  &ySigA_z_HANmessages_0X_RTPAccepted, 0 xFreS(0) SIGCODE(RTPAccepted)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),35,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0X_RTPAccepted = {xSignalParEC
  , (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0X_RTPAccepted
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1Q_RTPID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1Q_RTPID,
  xOffsetOf(yPDef_z_HANmessages_0X_RTPAccepted, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL RTPRefused
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),36,1)
******/
static xSignalNode ySigA_z_HANmessages_0Y_RTPRefused = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0Y_RTPRefused = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "RTPRefused" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z_HANmessages_0Y_RTPRefused),
  &ySigA_z_HANmessages_0Y_RTPRefused, 0 xFreS(0) SIGCODE(RTPRefused)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),36,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0Y_RTPRefused = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0Y_RTPRefused
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1Q_RTPID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1Q_RTPID,
  xOffsetOf(yPDef_z_HANmessages_0Y_RTPRefused, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*****
* SIGNAL Shutdown
* <<PACKAGE HANmessages>>
* #SDTREF(SDL,C:\Users\ZAHID\Desktop\HAN_v3\HANmessages.sun(2),161(45,40),37,1)
******/
static xSignalNode ySigA_z_HANmessages_0Z_Shutdown = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z_HANmessages_0Z_Shutdown = {xSignalEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPacR_z_HANmessages__HANmessages,
  "Shutdown" XCOMMON_EXTRAS, (xptrint)sizeof(yPDef_z_HANmessages_0Z_Shutdown),
  &ySigA_z_HANmessages_0Z_Shutdown, 0 xFreS(0) SIGCODE(Shutdown)
  xBreakB("#SDTREF(SDL,C:\\Users\\ZAHID\\Desktop\\HAN_v3\\HANmessages.sun(2),161(45,40),37,1)")
  xSigPrioPar(xDefaultPrioSignal) ZERO_OFFSET XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z_HANmessages_0Z_Shutdown = {xSignalParEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&ySigR_z_HANmessages_0Z_Shutdown
  xIdNames(" ") XCOMMON_EXTRAS, &ySrtR_z_HANmessages_1I_AppID,
  (tSDLTypeInfo *)&ySDL_z_HANmessages_1I_AppID,
  xOffsetOf(yPDef_z_HANmessages_0Z_Shutdown, Param1), (xptrint)0, (xbool)0
  XSPA_EXTRAS};
#endif

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
void yInit_HANmessages (void)
{
  static int IsCalled = 0;
  int  Temp;
  YINIT_TEMP_VARS
  if (IsCalled) {
    return;
  }
  IsCalled = 1;
  xInsertIdNode((xIdNode)&yPacR_z_HANmessages__HANmessages);
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1C_AppType);
#endif
#ifndef XOPTLIT
  xInsertIdNode((xIdNode)&yLitR_z_HANmessages_1C0_CTRL);
  xInsertIdNode((xIdNode)&yLitR_z_HANmessages_1C1_CRITICAL);
  xInsertIdNode((xIdNode)&yLitR_z_HANmessages_1C2_NULL);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1D_AppArray);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1E_TypeArray);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1F_ConsArray);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1G_PryArray);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1H_SetID);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1I_AppID);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1J_DevPriority);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1K_Charge);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1L_Consumption);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1M_FULL);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1N_Price);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1O_Storage);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1P_BidID);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z_HANmessages_1Q_RTPID);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_00_PowerON);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_00_PowerON);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_00_PowerON);
  xInsertIdNode((xIdNode)&ySPaR3_z_HANmessages_00_PowerON);
  xInsertIdNode((xIdNode)&ySPaR4_z_HANmessages_00_PowerON);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_01_PowerOFF);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_01_PowerOFF);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_02_Register);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_02_Register);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_02_Register);
  xInsertIdNode((xIdNode)&ySPaR3_z_HANmessages_02_Register);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_03_RegisterOK);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_03_RegisterOK);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_04_AddDevice);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_04_AddDevice);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_04_AddDevice);
  xInsertIdNode((xIdNode)&ySPaR3_z_HANmessages_04_AddDevice);
  xInsertIdNode((xIdNode)&ySPaR4_z_HANmessages_04_AddDevice);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_05_Unregister);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_05_Unregister);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_06_DeleteDev);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_06_DeleteDev);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_07_ConnectEV);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_07_ConnectEV);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_07_ConnectEV);
  xInsertIdNode((xIdNode)&ySPaR3_z_HANmessages_07_ConnectEV);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_08_DisconnectEV);
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_09_RegisterEV);
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0A_RegisterEVOK);
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0B_UnregisterEV);
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0C_EVready);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0C_EVready);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0D_ChargeCar);
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0E_RevisedBatt);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0E_RevisedBatt);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0F_MeteringData);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0F_MeteringData);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0G_MeteringSum);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0G_MeteringSum);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0H_ApproxBilling);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0H_ApproxBilling);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0I_getMetering);
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0J_SendMetering);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0J_SendMetering);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0K_RenewableE);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0K_RenewableE);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_0K_RenewableE);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0L_UseStorage);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0L_UseStorage);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0M_ResetCost);
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0N_Bid);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0N_Bid);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_0N_Bid);
  xInsertIdNode((xIdNode)&ySPaR3_z_HANmessages_0N_Bid);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0O_AcceptBid);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0O_AcceptBid);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_0O_AcceptBid);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0P_SaleEnergy);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0P_SaleEnergy);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_0P_SaleEnergy);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0Q_BidAccepted);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0Q_BidAccepted);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0R_BidRefused);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0R_BidRefused);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0S_getBatteryCharge);
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0T_SendBatteryCharge);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0T_SendBatteryCharge);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0U_ReviseBattery);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0U_ReviseBattery);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0V_RTP);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0V_RTP);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_0V_RTP);
  xInsertIdNode((xIdNode)&ySPaR3_z_HANmessages_0V_RTP);
  xInsertIdNode((xIdNode)&ySPaR4_z_HANmessages_0V_RTP);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0W_AcceptRTP);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0W_AcceptRTP);
  xInsertIdNode((xIdNode)&ySPaR2_z_HANmessages_0W_AcceptRTP);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0X_RTPAccepted);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0X_RTPAccepted);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0Y_RTPRefused);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0Y_RTPRefused);
#endif
  xInsertIdNode((xIdNode)&ySigR_z_HANmessages_0Z_Shutdown);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z_HANmessages_0Z_Shutdown);
#endif
}
